version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: random_eats_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - random_eats_network

volumes:
  postgres_data:

networks:
  random_eats_network:
    driver: bridge 
